# Generated by Django 5.0.1 on 2024-02-01 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('mines_count', models.IntegerField()),
                ('field', models.JSONField(blank=True, null=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('field_with_mines', models.JSONField(blank=True, null=True)),
                ('move_is_first', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
