# Generated by Django 5.0.1 on 2024-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='move_is_first',
        ),
        migrations.AddField(
            model_name='game',
            name='first_move',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
